---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-api-operator-config
  namespace: capi-operator-system
data:
  values.yaml: |
    core:
      cluster-api:
        namespace: capi-system
        version: v1.14.2
        manager:
          featureGates:
            MachinePool: false
            ClusterTopology: false
            RuntimeSDK: false
            MachineSetPreflightChecks: true
    bootstrap:
      kubeadm:
        namespace: capi-kubeadm-bootstrap-system
        version: v1.14.2
    controlPlane:
      kubeadm:
        namespace: capi-kubeadm-control-plane-system
        version: v1.14.2
    infrastructure:
      openstack:
        namespace: capo-system
        version: v0.14.8
