---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-api-operator-config
  namespace: capi-operator-system
data:
  values.yaml: |
    core: capi-system:cluster-api:v1.7.2
    bootstrap: capi-kubeadm-bootstrap-system:kubeadm:v1.7.2
    controlPlane: capi-kubeadm-control-plane-system:kubeadm:v1.7.2
    infrastructure: capo-system:openstack:v0.10.5
    manager:
      featureGates:
        core:
          MachinePool: false
          ClusterResourceSet: false
          ClusterTopology: false
          RuntimeSDK: false
          MachineSetPreflightChecks: true
